cameras:
  camera_1:
    camera_ip: 192.168.1.5
    camera_port: 8000
    camera_name: 'Loft'
  camera_2:
    camera_ip: 192.168.1.6
    camera_port: 8000
    camera_name: 'Kitchen'
  camera_3:
    camera_ip: 192.168.1.9
    camera_port: 8000
    camera_name: 'Basement'

